import { resourceManager, uniformLayouts } from '@shaderlab/api';
import type { Scene } from '@shaderlab/api';

const ATOM_FACTOR = 1024.0;

/** Pre-baked structural data loaded from a JSON asset file (generated by
 *  generate_softbody.py / generate_softbody.mjs). Contains axis-aligned rest
 *  positions centered at origin — the runtime applies a random rotation +
 *  the entity's Transform translation when seeding GPU buffers. */
interface SoftBodyAsset {
    meta: {
        gridN: number;
        cellSize: number;
        clusterRadius: number;
        mass: number;
        particleCount: number;
        clusterCount: number;
        clusterEntries: number;
        surfaceVertexCount: number;
    };
    positions: number[][];       // [particleCount][4] — x, y, z, invMass
    surfaceIndices: number[];     // flat u32 triangle indices
    clusters: { restCom: number[]; count: number; offset: number }[];
    clusterIndices: number[];    // flat u32 particle indices per cluster
    restOffsets: number[][];     // [clusterEntries][3] — relative to cluster rest COM
}

/**
 * Uniform random rotation matrix (row-major 3x3) via Shoemake's algorithm
 * ("Uniform Random Rotations", 1992). Returns 9 floats; `result[3*row + col]`
 * is the entry at row `row`, column `col`. Apply as `p' = R * p`.
 */
function randomRotationMatrix(): Float32Array {
    const u1 = Math.random();
    const u2 = Math.random() * Math.PI * 2;
    const u3 = Math.random() * Math.PI * 2;
    const s1 = Math.sqrt(1 - u1);
    const s2 = Math.sqrt(u1);
    // Unit quaternion (w, x, y, z).
    const w = s1 * Math.cos(u3);
    const x = s1 * Math.sin(u3);
    const y = s2 * Math.cos(u2);
    const z = s2 * Math.sin(u2);

    const xx = x * x, yy = y * y, zz = z * z;
    const xy = x * y, xz = x * z, yz = y * z;
    const wx = w * x, wy = w * y, wz = w * z;

    return new Float32Array([
        1 - 2 * (yy + zz), 2 * (xy - wz),      2 * (xz + wy),
        2 * (xy + wz),      1 - 2 * (xx + zz), 2 * (yz - wx),
        2 * (xz - wy),      2 * (yz + wx),      1 - 2 * (xx + yy),
    ]);
}

interface SysGpu {
    eid: number;
    particleCount: number;
    clusterCount: number;
    clusterEntries: number;
    clusterSizes: Uint32Array;
    surfaceVertexCount: number;
    positions: GPUBuffer;
    predicted: GPUBuffer;
    velocities: GPUBuffer;
    clusters: GPUBuffer;
    clusterIndices: GPUBuffer;
    restOffsets: GPUBuffer;
    corrections: GPUBuffer;
    counts: GPUBuffer;
    surfaceIndices: GPUBuffer;
    ubo: GPUBuffer;
    predictBind: GPUBindGroup;
    solveBind: GPUBindGroup;
    applyBind: GPUBindGroup;
    integrateBind: GPUBindGroup;
    debugLinesBind: GPUBindGroup;
    drawBind: GPUBindGroup;
    seeded: boolean;
}

/**
 * GPU PBD (Position-Based Dynamics) soft-body manager using **Shape Matching**
 * constraints only — no distance constraints.
 *
 * Each particle owns one cluster that includes itself + every neighbor within
 * Chebyshev radius `clusterRadius` (component-tunable). Clusters overlap, so a
 * particle typically belongs to several clusters. Solving happens in two
 * phases per iteration:
 *
 *   1. Solve pass (one thread per cluster): compute current center of mass,
 *      covariance A = sum( (p_i - com) * q_i^T ), polar-decompose A to extract
 *      rotation R, compute goal = com + R * q_i for each member, then
 *      fixed-point atomicAdd the correction (goal - p_i) * stiffness into
 *      per-particle accumulators + a weight counter.
 *   2. Integrate pass (one thread per particle): divide accumulated correction
 *      by weight (Jacobi average), apply to predicted position, integrate
 *      velocity from position delta, do floor collision, then clear the
 *      accumulators for the next iteration.
 *
 * No graph coloring is required: no thread writes `predicted` during solving,
 * so all clusters run fully in parallel.
 *
 * Fixed-point encoding (atomFactor = 1024) is used because WebGPU only supports
 * atomicAdd on `atomic<i32>`/`atomic<u32>`, not on `f32`. Corrections are
 * scaled by atomFactor, rounded to i32, atomicAdd'd, and decoded back to f32
 * in the Integrate pass.
 */
export class PbdManager {
    private systems = new Map<number, SysGpu>();
    private frameLog = 0;
    private asset: SoftBodyAsset | null = null;

    // Debug overlay state (toggled by reset.js script: C = toggle, [ / ] = cycle)
    private debugEnabled = false;
    private debugCluster = 0;

    /**
     * Fetch the pre-baked soft-body asset from the app's folder. Called by
     * the plugin's appLoaded lifecycle (after scene + render graph are ready).
     * The asset path comes from PbdSoftBodyComponent.asset (relative to appBase).
     * The asset persists across re-seeds (R key) — only GPU buffers are rebuilt.
     */
    async loadAsset(scene: Scene, appBase: string): Promise<void> {
        let assetPath = 'softbody_asset.json';
        for (const [, eid] of scene.entityKeyMap) {
            const p = scene.getField(eid, 'PbdSoftBodyComponent', 'asset');
            if (typeof p === 'string') { assetPath = p; break; }
        }
        const url = `${appBase}/${assetPath}`;
        const resp = await fetch(url);
        if (!resp.ok) throw new Error(`[pbd] asset not found: ${url}`);
        this.asset = await resp.json() as SoftBodyAsset;
        const m = this.asset.meta;
        console.log(`[pbd] loaded asset ${assetPath}: gridN=${m.gridN} particles=${m.particleCount} clusters=${m.clusterCount} entries=${m.clusterEntries}`);
    }

    setDebugEnabled(on: boolean): void { this.debugEnabled = on; }
    isDebugEnabled(): boolean { return this.debugEnabled; }
    cycleDebugCluster(delta: number): void {
        let max = 0;
        for (const sys of this.systems.values()) max = Math.max(max, sys.clusterCount);
        if (max === 0) return;
        this.debugCluster = (this.debugCluster + delta + max) % max;
    }
    getDebugClusterInfo(): { cluster: number, total: number, memberCount: number } {
        let total = 0;
        let memberCount = 0;
        for (const sys of this.systems.values()) {
            total = Math.max(total, sys.clusterCount);
            const cid = this.debugCluster % sys.clusterCount;
            memberCount = sys.clusterSizes[cid];
        }
        return { cluster: this.debugCluster, total, memberCount };
    }

    clear(): void {
        for (const sys of this.systems.values()) {
            this.destroySys(sys);
        }
        this.systems.clear();
        this.frameLog = 0;
        this.debugEnabled = false;
        this.debugCluster = 0;
    }

    /** Destroy all GPU buffers held by a SysGpu entry. */
    private destroySys(sys: SysGpu): void {
        sys.positions.destroy();
        sys.predicted.destroy();
        sys.velocities.destroy();
        sys.clusters.destroy();
        sys.clusterIndices.destroy();
        sys.restOffsets.destroy();
        sys.corrections.destroy();
        sys.counts.destroy();
        sys.surfaceIndices.destroy();
        sys.ubo.destroy();
    }

    simulate(
        encoder: GPUCommandEncoder,
        scene: Scene,
        predictPipeline: GPUComputePipeline,
        solvePipeline: GPUComputePipeline,
        applyPipeline: GPUComputePipeline,
        integratePipeline: GPUComputePipeline,
        entities: readonly number[],
        dt: number,
        time: number,
        predictTgs: number,
        solveTgs: number,
        applyTgs: number,
        integrateTgs: number,
    ): void {
        const dev = resourceManager.device;
        const safeDt = Math.min(Math.max(dt, 0.0), 1.0 / 30.0);

        // Clean up SysGpu entries for entities that no longer exist in the
        // scene (handles scene reloads via loadJSON, entity removal, etc.
        // without a full app unload). Without this, GPU buffers leak and
        // recycled entity IDs would find stale data.
        if (this.systems.size > 0) {
            const valid = new Set(entities);
            for (const [eid, sys] of this.systems) {
                if (!valid.has(eid)) {
                    this.destroySys(sys);
                    this.systems.delete(eid);
                }
            }
        }

        if (this.frameLog < 5) {
            console.log(`[pbd] frame ${this.frameLog}: dt=${dt.toFixed(4)}s safeDt=${safeDt.toFixed(4)}s entities=${entities.length}`);
            this.frameLog++;
        }
        for (const eid of entities) {
            const sys = this.ensure(scene, eid);
            this.writeUbo(dev, sys, scene, eid, safeDt, time);

            // 1. Predict — bake gravity into `predicted` (p_pred = p + (v + g·dt)·dt).
            const passP = encoder.beginComputePass();
            passP.setPipeline(predictPipeline);
            passP.setBindGroup(0, sys.predictBind);
            passP.dispatchWorkgroups(Math.ceil(sys.particleCount / predictTgs));
            passP.end();

            // 2. Solve + Apply (repeated — Jacobi needs more iterations than GS).
            //    Solve atomic-accumulates corrections; Apply averages and writes
            //    them back into `predicted` only — positions/velocities are
            //    untouched until Integrate runs once below.
            const iters = this.numField(scene, eid, 'solverIterations') ?? 8;
            for (let iter = 0; iter < iters; iter++) {
                const passS = encoder.beginComputePass();
                passS.setPipeline(solvePipeline);
                passS.setBindGroup(0, sys.solveBind);
                passS.dispatchWorkgroups(Math.ceil(sys.clusterCount / solveTgs));
                passS.end();

                const passA = encoder.beginComputePass();
                passA.setPipeline(applyPipeline);
                passA.setBindGroup(0, sys.applyBind);
                passA.dispatchWorkgroups(Math.ceil(sys.particleCount / applyTgs));
                passA.end();
            }

            // 3. Integrate — runs ONCE per frame. Velocity is derived from the
            //    total position delta (final predicted − start-of-frame position)
            //    so the gravity contribution baked into `predicted` survives.
            const passI = encoder.beginComputePass();
            passI.setPipeline(integratePipeline);
            passI.setBindGroup(0, sys.integrateBind);
            passI.dispatchWorkgroups(Math.ceil(sys.particleCount / integrateTgs));
            passI.end();
        }
    }

    draw(
        pass: GPURenderPassEncoder,
        scene: Scene,
        pipeline: GPURenderPipeline,
        entities: readonly number[],
    ): void {
        for (const eid of entities) {
            const sys = this.systems.get(eid);
            if (!sys) continue;
            pass.setPipeline(pipeline);
            pass.setBindGroup(1, sys.drawBind);
            pass.draw(sys.surfaceVertexCount);
        }
    }

    /**
     * Debug overlay: draw the selected cluster as a "star" of lines from its
     * current center of mass to each member particle. No-op when debug is off.
     * The cluster index is written to the pbdParams UBO (debugCluster field)
     * every frame in writeUbo, so the line shader picks it up automatically.
     */
    drawDebug(
        pass: GPURenderPassEncoder,
        pipeline: GPURenderPipeline,
        entities: readonly number[],
    ): void {
        if (!this.debugEnabled) return;
        for (const eid of entities) {
            const sys = this.systems.get(eid);
            if (!sys) continue;
            const cid = this.debugCluster % sys.clusterCount;
            const memberCount = sys.clusterSizes[cid];
            pass.setPipeline(pipeline);
            pass.setBindGroup(1, sys.debugLinesBind);
            pass.draw(memberCount * 2);
        }
    }

    /* ── per-system GPU resources ───────────────────── */

    private ensure(scene: Scene, eid: number): SysGpu {
        const existing = this.systems.get(eid);
        if (existing && existing.seeded) return existing;
        if (!this.asset) throw new Error('[pbd] no asset loaded — call loadAsset() first (appLoaded lifecycle)');

        const dev = resourceManager.device;
        const { meta, positions: aPos, surfaceIndices: aSurf, clusters: aCl, clusterIndices: aCI, restOffsets: aRO } = this.asset;
        const particleCount = meta.particleCount;
        const clusterCount = meta.clusterCount;
        const clusterEntries = meta.clusterEntries;
        const surfaceVertexCount = meta.surfaceVertexCount;

        const tr = scene.getField(eid, 'Transform', 'position') as number[] | undefined;
        const cx = tr?.[0] ?? 0;
        const cy = tr?.[1] ?? 4;
        const cz = tr?.[2] ?? 0;
        const totalMass = this.numField(scene, eid, 'mass') ?? meta.mass;
        const invMass = particleCount / totalMass;

        // ── apply fresh random rotation + translation to asset data ──────
        // The asset stores axis-aligned positions centered at origin. Each
        // re-seed draws a new rotation so the cube drops with a different
        // orientation. restCom and restOffsets are rotated consistently so
        // shape matching's "rest shape" matches the spawn orientation.
        const stride = 16;
        const rot = randomRotationMatrix();
        const rotVec = (ox: number, oy: number, oz: number): [number, number, number] => [
            rot[0] * ox + rot[1] * oy + rot[2] * oz,
            rot[3] * ox + rot[4] * oy + rot[5] * oz,
            rot[6] * ox + rot[7] * oy + rot[8] * oz,
        ];

        const posInit = new Float32Array(particleCount * 4);
        const velInit = new Float32Array(particleCount * 4);
        for (let i = 0; i < particleCount; i++) {
            const [rx, ry, rz] = rotVec(aPos[i][0], aPos[i][1], aPos[i][2]);
            posInit[i * 4 + 0] = cx + rx;
            posInit[i * 4 + 1] = cy + ry;
            posInit[i * 4 + 2] = cz + rz;
            posInit[i * 4 + 3] = invMass;
        }

        // ── cluster buffer: struct Cluster { restCom: vec3f, count: u32, offset: u32 } — 32B stride ──
        const CLUSTER_STRIDE = 8; // 32 bytes = 8 × u32/f32
        const clusterBuf = new ArrayBuffer(clusterCount * 32);
        const cF32 = new Float32Array(clusterBuf);
        const cU32 = new Uint32Array(clusterBuf);
        const clusterSizes = new Uint32Array(clusterCount);
        for (let c = 0; c < clusterCount; c++) {
            const cl = aCl[c];
            clusterSizes[c] = cl.count;
            const [rx, ry, rz] = rotVec(cl.restCom[0], cl.restCom[1], cl.restCom[2]);
            cF32[c * CLUSTER_STRIDE + 0] = cx + rx;
            cF32[c * CLUSTER_STRIDE + 1] = cy + ry;
            cF32[c * CLUSTER_STRIDE + 2] = cz + rz;
            cU32[c * CLUSTER_STRIDE + 3] = cl.count;
            cU32[c * CLUSTER_STRIDE + 4] = cl.offset;
        }

        // clusterIndices: plain copy (index references, no rotation needed)
        const indices = new Uint32Array(clusterEntries);
        for (let i = 0; i < clusterEntries; i++) indices[i] = aCI[i];

        // restOffsets: rotate each offset vector (relative to cluster COM)
        const restOff = new Float32Array(clusterEntries * 4); // array<vec3f> stride 16
        for (let i = 0; i < clusterEntries; i++) {
            const [rx, ry, rz] = rotVec(aRO[i][0], aRO[i][1], aRO[i][2]);
            restOff[i * 4 + 0] = rx;
            restOff[i * 4 + 1] = ry;
            restOff[i * 4 + 2] = rz;
        }

        // surfaceIndices: plain copy (index references, no rotation needed)
        const surfaceIdx = new Uint32Array(surfaceVertexCount);
        for (let i = 0; i < surfaceVertexCount; i++) surfaceIdx[i] = aSurf[i];

        console.log(`[pbd] seeded from asset: gridN=${meta.gridN} particles=${particleCount} invMass=${invMass.toFixed(1)} clusters=${clusterCount} entries=${clusterEntries} (random spawn rotation applied)`);

        // ── create all buffers with mappedAtCreation ────────────────────
        const positions = dev.createBuffer({
            size: particleCount * stride,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Float32Array(positions.getMappedRange()).set(posInit);
        positions.unmap();

        const predicted = dev.createBuffer({
            size: particleCount * stride,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Float32Array(predicted.getMappedRange()).set(posInit);
        predicted.unmap();

        const velocities = dev.createBuffer({
            size: particleCount * stride,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Float32Array(velocities.getMappedRange()).set(velInit);
        velocities.unmap();

        const clusters = dev.createBuffer({
            size: clusterCount * 32,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Uint8Array(clusters.getMappedRange()).set(new Uint8Array(clusterBuf));
        clusters.unmap();

        const clusterIndices = dev.createBuffer({
            size: clusterEntries * 4,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Uint32Array(clusterIndices.getMappedRange()).set(indices);
        clusterIndices.unmap();

        // array<vec3f> has stride 16 (vec3f align rounds up). Use Float32 view.
        const restOffsets = dev.createBuffer({
            size: clusterEntries * 16,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Float32Array(restOffsets.getMappedRange()).set(restOff);
        restOffsets.unmap();

        const corrections = dev.createBuffer({
            size: particleCount * stride,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        corrections.unmap();

        const counts = dev.createBuffer({
            size: particleCount * 4,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        counts.unmap();

        const surfaceIndicesBuf = dev.createBuffer({
            size: surfaceVertexCount * 4,
            usage: GPUBufferUsage.STORAGE | GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        new Uint32Array(surfaceIndicesBuf.getMappedRange()).set(surfaceIdx);
        surfaceIndicesBuf.unmap();

        // ── UBO ────────────────────────────────────────────────────────
        const layout = uniformLayouts.get('pbdParams');
        const uboBytes = layout.byteSize;
        const ubo = dev.createBuffer({
            size: uboBytes,
            usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
            mappedAtCreation: true,
        });
        {
            const ab = new ArrayBuffer(uboBytes);
            const f = new Float32Array(ab);
            const u = new Uint32Array(ab);
            const gravity = this.numField(scene, eid, 'gravity') ?? -9.81;
            const damping = this.numField(scene, eid, 'damping') ?? 0.995;
            const iters = this.numField(scene, eid, 'solverIterations') ?? 8;
            const restitution = this.numField(scene, eid, 'restitution') ?? 0.3;
            const stiff = this.numField(scene, eid, 'compliance') ?? 0;
            layout.write(f, 'dt', 0.016);
            layout.write(f, 'time', 0);
            layout.write(f, 'gravityY', gravity);
            layout.write(f, 'damping', damping);
            layout.writeU32(u, 'solverIterations', iters);
            layout.writeU32(u, 'particleCount', particleCount);
            layout.write(f, 'restitution', restitution);
            layout.writeU32(u, 'clusterCount', clusterCount);
            layout.write(f, 'atomFactor', ATOM_FACTOR);
            layout.write(f, 'stiffness', 1.0 - Math.min(Math.max(stiff, 0), 0.95));
            layout.writeU32(u, 'debugCluster', 0);
            new Uint8Array(ubo.getMappedRange()).set(new Uint8Array(ab));
            ubo.unmap();
        }

        // ── bind groups ────────────────────────────────────────────────
        const predictBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdPredict'),
            entries: [
                { binding: 0, resource: { buffer: positions } },
                { binding: 1, resource: { buffer: predicted } },
                { binding: 2, resource: { buffer: velocities } },
                { binding: 3, resource: { buffer: ubo } },
            ],
        });
        const solveBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdSolve'),
            entries: [
                { binding: 0, resource: { buffer: predicted } },
                { binding: 1, resource: { buffer: clusters } },
                { binding: 2, resource: { buffer: clusterIndices } },
                { binding: 3, resource: { buffer: restOffsets } },
                { binding: 4, resource: { buffer: corrections } },
                { binding: 5, resource: { buffer: counts } },
                { binding: 6, resource: { buffer: ubo } },
            ],
        });
        const applyBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdApply'),
            entries: [
                { binding: 0, resource: { buffer: predicted } },
                { binding: 1, resource: { buffer: corrections } },
                { binding: 2, resource: { buffer: counts } },
                { binding: 3, resource: { buffer: ubo } },
            ],
        });
        const integrateBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdIntegrate'),
            entries: [
                { binding: 0, resource: { buffer: positions } },
                { binding: 1, resource: { buffer: predicted } },
                { binding: 2, resource: { buffer: velocities } },
                { binding: 3, resource: { buffer: ubo } },
            ],
        });
        const drawBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdDraw'),
            entries: [
                { binding: 0, resource: { buffer: positions } },
                { binding: 1, resource: { buffer: surfaceIndicesBuf } },
            ],
        });
        const debugLinesBind = dev.createBindGroup({
            layout: resourceManager.namedLayout('pbdDebugLines'),
            entries: [
                { binding: 0, resource: { buffer: positions } },
                { binding: 1, resource: { buffer: clusters } },
                { binding: 2, resource: { buffer: clusterIndices } },
                { binding: 3, resource: { buffer: ubo } },
            ],
        });

        const sys: SysGpu = {
            eid, particleCount, clusterCount, clusterEntries, clusterSizes, surfaceVertexCount,
            positions, predicted, velocities, clusters, clusterIndices, restOffsets,
            corrections, counts, surfaceIndices: surfaceIndicesBuf, ubo,
            predictBind, solveBind, applyBind, integrateBind, debugLinesBind, drawBind,
            seeded: true,
        };
        this.systems.set(eid, sys);
        return sys;
    }

    private writeUbo(dev: GPUDevice, sys: SysGpu, scene: Scene, eid: number, dt: number, time: number): void {
        const layout = uniformLayouts.get('pbdParams');
        const ab = new ArrayBuffer(layout.byteSize);
        const f = new Float32Array(ab);
        const u = new Uint32Array(ab);

        const gravity = this.numField(scene, eid, 'gravity') ?? -9.81;
        const damping = this.numField(scene, eid, 'damping') ?? 0.995;
        const iters = this.numField(scene, eid, 'solverIterations') ?? 8;
        const restitution = this.numField(scene, eid, 'restitution') ?? 0.3;
        const compliance = this.numField(scene, eid, 'compliance') ?? 0;

        layout.write(f, 'dt', dt);
        layout.write(f, 'time', time);
        layout.write(f, 'gravityY', gravity);
        layout.write(f, 'damping', damping);
        layout.writeU32(u, 'solverIterations', iters);
        layout.writeU32(u, 'particleCount', sys.particleCount);
        layout.write(f, 'restitution', restitution);
        layout.writeU32(u, 'clusterCount', sys.clusterCount);
        layout.write(f, 'atomFactor', ATOM_FACTOR);
        layout.write(f, 'stiffness', 1.0 - Math.min(Math.max(compliance, 0), 0.95));
        layout.writeU32(u, 'debugCluster', this.debugCluster);

        dev.queue.writeBuffer(sys.ubo, 0, ab);
    }

    private numField(scene: Scene, eid: number, field: string): number | undefined {
        const v = scene.getField(eid, 'PbdSoftBodyComponent', field);
        return typeof v === 'number' ? v : undefined;
    }
}
